// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQJgDLydE3zyLqp2ugy5BHdQc4rMC-XY',
    appId: '1:846154259970:web:5d2fe93c0b24b7edbb911b',
    messagingSenderId: '846154259970',
    projectId: 'skillswap-2c99b',
    authDomain: 'skillswap-2c99b.firebaseapp.com',
    storageBucket: 'skillswap-2c99b.firebasestorage.app',
    measurementId: 'G-VH8G2Y5RZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtsWodP7xerh3wOrH0KRolAhtgL5c1Bk',
    appId: '1:846154259970:android:faaeb4e6a55ed0e1bb911b',
    messagingSenderId: '846154259970',
    projectId: 'skillswap-2c99b',
    storageBucket: 'skillswap-2c99b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyEVVWUoEAS62vPRw7_ZjJ3tGmzfAQZDk',
    appId: '1:846154259970:ios:925e19136e0ded6bbb911b',
    messagingSenderId: '846154259970',
    projectId: 'skillswap-2c99b',
    storageBucket: 'skillswap-2c99b.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyEVVWUoEAS62vPRw7_ZjJ3tGmzfAQZDk',
    appId: '1:846154259970:ios:925e19136e0ded6bbb911b',
    messagingSenderId: '846154259970',
    projectId: 'skillswap-2c99b',
    storageBucket: 'skillswap-2c99b.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQJgDLydE3zyLqp2ugy5BHdQc4rMC-XY',
    appId: '1:846154259970:web:26748a6afec4bf0bbb911b',
    messagingSenderId: '846154259970',
    projectId: 'skillswap-2c99b',
    authDomain: 'skillswap-2c99b.firebaseapp.com',
    storageBucket: 'skillswap-2c99b.firebasestorage.app',
    measurementId: 'G-K2RB0XFZHE',
  );
}
